---
- name: "Bash | Darwin | Detect oh-my-bash"
  ansible.builtin.stat:
    path: "{{ ansible_user_dir | default(ansible_env.HOME) }}/.oh-my-bash"
  register: ohmybash

- name: "Bash | Darwin | Register oh-my-bash state"
  ansible.builtin.set_fact:
    ohmybash_is_installed: "{{ ohmybash.stat.exists }}"

- name: "Bash | Darwin | Debug ohmybash_is_installed"
  ansible.builtin.debug:
    var: ohmybash_is_installed

- name: "Bash | Darwin | Install oh-my-bash"
  when: not ohmybash_is_installed
  block:
    - name: "Bash | Darwin | Download oh-my-bash Install Script"
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh
        dest: "{{ ansible_user_dir | default(ansible_env.HOME) }}/oh-my-bash.install.sh"
        force: true
        mode: "0755"
      notify:
        - "Bash | Cleanup oh-my-bash install script"

    - name: "Bash | Darwin | Run the install script"
      ansible.builtin.script:
        cmd: "{{ ansible_user_dir | default(ansible_env.HOME) }}/oh-my-bash.install.sh"

- name: "Bash | Darwin | Copy .bashrc"
  ansible.builtin.copy:
    src: ".bashrc"
    dest: "{{ ansible_user_dir | default(ansible_env.HOME) }}/.bashrc"
    mode: "0644"

- name: "Bash | Darwin | Copy .profile"
  ansible.builtin.copy:
    src: ".profile"
    dest: "{{ ansible_user_dir | default(ansible_env.HOME) }}/.profile"
    mode: "0644"

- name: "Bash | Darwin | Copy custom bash config"
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir | default(ansible_env.HOME) }}/.config/"
    src: "bash"
    mode: "0644"
    directory_mode: 0755
    force: true

- name: "Bash | Darwin | Ensure .local/bin directory exists"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.local/bin"
    state: directory
    mode: "0755"

- name: "Bash | Darwin | Copy bash scripts to bin directory without .sh extension"
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ ansible_user_dir }}/.local/bin/{{ item | basename | regex_replace('\\.sh$', '') }}"
    mode: "0755"
  with_fileglob:
    - "bash/scripts/*.sh"

- name: "Bash | Darwin | Copy custom bash theme"
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir | default(ansible_env.HOME) }}/.oh-my-bash/custom/"
    src: "themes"
    directory_mode: 0755
    mode: "0644"
    force: true

- name: "Bash | Darwin | Set private variables"
  ansible.builtin.template:
    dest: "{{ ansible_user_dir | default(ansible_env.HOME) }}/.config/bash/.bash_private"
    src: ".bash_private.j2"
    mode: "0644"
  no_log: false
