---
- name: "GCC | Windows | Check if Chocolatey is installed"
  ansible.builtin.win_shell: |
    $ChocoInstalled = $false
    if (Get-Command choco -ErrorAction SilentlyContinue) {
      $ChocoInstalled = $true
    }
    $ChocoInstalled
  register: choco_check
  changed_when: false

- name: "GCC | Windows | Install Chocolatey"
  ansible.builtin.win_shell: |
    Set-ExecutionPolicy Bypass -Scope Process -Force
    [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
    iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
  when: choco_check.stdout | trim == "False"

- name: "GCC | Windows | Install MinGW (includes GCC) via Chocolatey"
  ansible.windows.win_chocolatey:
    name: mingw
    state: present

- name: "GCC | Windows | Install Make via Chocolatey"
  ansible.windows.win_chocolatey:
    name: make
    state: present

- name: "GCC | Windows | Install additional build tools"
  ansible.windows.win_chocolatey:
    name:
      - git
      - ripgrep
      - wget
      - fd
      - unzip
      - gzip
    state: present
