---
- name: Run Darwin Tasks
  ansible.builtin.import_tasks: Darwin.yml
  when: ansible_os_family == 'Darwin'

- name: "raycas | Config folder"
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/raycast"
    state: directory


- name: "raycast | Create symlink to role files directory"
  ansible.builtin.file:
    src: "{{ role_path }}/files/raycast/"
    dest: "{{ ansible_user_dir }}/.config/raycast"
    state: link
    force: true
